package main

import (
	"log"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/rayer/llm-wiki-bff/internal/config"
	"github.com/rayer/llm-wiki-bff/internal/firestore"
	"github.com/rayer/llm-wiki-bff/internal/gcs"
	"github.com/rayer/llm-wiki-bff/internal/handler"
	"github.com/rayer/llm-wiki-bff/internal/llm"
	"github.com/rayer/llm-wiki-bff/internal/search"

	_ "github.com/rayer/llm-wiki-bff/docs" // swagger docs (generated by swag init)
)

//	@title			LLM Wiki BFF API
//	@version		1.0
//	@description	Backend-for-frontend API for the LLM Wiki project. Serves wiki sources and concepts with full-text search, import, and pipeline status.
//	@contact.name	LLM Wiki Team
//
//	@BasePath	/

func main() {
	cfg, err := config.Load(".")
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Init GCS client
	gcsClient, err := gcs.NewClient(cfg.Bucket, cfg.UserID, cfg.ProjectID)
	if err != nil {
		log.Fatalf("Failed to create GCS client: %v", err)
	}
	log.Printf("GCS client ready: gs://%s/users/%s/projects/%s/", cfg.Bucket, cfg.UserID, cfg.ProjectID)

	// Init Firestore client
	fsClient, err := firestore.NewClient(cfg.GCPProject, cfg.UserID, cfg.ProjectID)
	if err != nil {
		log.Printf("WARNING: Firestore client not available: %v", err)
	}

	// Search metadata index
	idx := search.NewIndex()
	if err := idx.Build(gcsClient); err != nil {
		log.Printf("WARNING: Search index build failed: %v", err)
	}
	log.Printf("Search metadata index: %d sources, %d concepts", idx.SourceCount(), idx.ConceptCount())

	// LLM client (optional — query works without it)
	llmClient := llm.NewClient(cfg.DeepSeekAPIKey)
	if llmClient != nil {
		log.Printf("LLM client: DeepSeek ready")
	} else {
		log.Printf("LLM client: DEEPSEEK_API_KEY not set — query synthesis disabled")
	}

	// Query expander (lifestyle domain for MVP)
	expander, err := llm.NewExpander(llmClient, "lifestyle")
	if err != nil {
		log.Printf("Query expander: %v", err)
	} else if expander != nil {
		log.Printf("Query expander: lifestyle domain ready")
	}

	// Handlers
	h := handler.New(gcsClient, fsClient, idx, llmClient, expander)

	// Gin router
	r := gin.Default()

	// CORS
	r.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}
		c.Next()
	})

	// ── Swagger UI ──
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ── API ──
	api := r.Group("/api")
	{
		api.POST("/query", h.Query)               // {"q": "...", "mode": "wiki|full"}
		api.GET("/sources", h.ListSources)       // list compiled wiki sources
		api.GET("/sources/:slug", h.GetSource)   // get single source content
		api.GET("/concepts", h.ListConcepts)     // list wiki concepts (including drafts)
		api.GET("/concepts/:slug", h.GetConcept) // get single concept
		api.POST("/import", h.Import)            // bookmark import (placeholder)
		api.GET("/status", h.Status)             // pipeline status

		// Metrics (Grafana)
		api.GET("/metrics", h.Metrics)         // pipeline execution metrics
		r.GET("/metrics", h.PrometheusMetrics) // Prometheus format (root level)

		// Raw content management
		api.POST("/raw/upload", h.UploadRaw)             // upload .md file to raw/
		api.POST("/raw/scrape", h.ScrapeRaw)             // scrape URL → raw/
		api.POST("/raw/generate-title", h.GenerateTitle) // LLM title from content

		// Pipeline
		api.POST("/pipeline/run", h.RunPipeline) // trigger OLW pipeline
	}

	// ── Static frontend ──
	r.StaticFile("/", "./static/index.html")
	r.Static("/static", "./static")
	r.NoRoute(func(c *gin.Context) {
		// SPA fallback: serve index.html for non-API routes
		if !strings.HasPrefix(c.Request.URL.Path, "/api") {
			c.File("./static/index.html")
		}
	})

	log.Printf("BFF listening on :%s", cfg.Port)
	log.Printf("Swagger UI: http://localhost:%s/swagger/index.html", cfg.Port)
	log.Fatal(r.Run(":" + cfg.Port))
}
