package main

import (
	"context"
	"log"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/rayer/llm-wiki-bff/internal/auth"
	conceptcache "github.com/rayer/llm-wiki-bff/internal/cache"
	"github.com/rayer/llm-wiki-bff/internal/config"
	"github.com/rayer/llm-wiki-bff/internal/firestore"
	"github.com/rayer/llm-wiki-bff/internal/gcs"
	"github.com/rayer/llm-wiki-bff/internal/handler"
	handlerv1 "github.com/rayer/llm-wiki-bff/internal/handler/v1"
	"github.com/rayer/llm-wiki-bff/internal/llm"
	"github.com/rayer/llm-wiki-bff/internal/middleware"
	"github.com/rayer/llm-wiki-bff/internal/observability"
	"github.com/rayer/llm-wiki-bff/internal/search"

	_ "github.com/rayer/llm-wiki-bff/docs" // swagger docs (generated by swag init)
)

//	@title			LLM Wiki BFF API
//	@version		1.0
//	@description	Backend-for-frontend API for the LLM Wiki project. Serves wiki sources and concepts with full-text search, import, and pipeline status.
//	@contact.name	LLM Wiki Team
//
//	@BasePath	/
//
//	@securityDefinitions.apikey	DevUserAuth
//	@in							header
//	@name						X-User-ID
//	@description				DEV mode user identity header. Required when dev_jwt=true.
//
//	@securityDefinitions.apikey	ProjectHeader
//	@in							header
//	@name						X-Project-ID
//	@description				Project identifier header.

func main() {
	cfg, err := config.Load(".")
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Init GCS client
	gcsClient, err := gcs.NewClient(cfg.Bucket, cfg.UserID, cfg.ProjectID)
	if err != nil {
		log.Fatalf("Failed to create GCS client: %v", err)
	}
	log.Printf("GCS client ready: gs://%s/users/%s/projects/%s/", cfg.Bucket, cfg.UserID, cfg.ProjectID)

	// Init Firestore client
	fsClient, err := firestore.NewClient(cfg.GCPProject, cfg.UserID, cfg.ProjectID)
	if err != nil {
		log.Printf("WARNING: Firestore client not available: %v", err)
	} else {
		auth.CreateTestUser(context.Background(), fsClient.Raw())
	}

	// Search metadata index
	idx := search.NewIndex()
	if err := idx.Build(gcsClient); err != nil {
		log.Printf("WARNING: Search index build failed: %v", err)
	}
	log.Printf("Search metadata index: %d sources, %d concepts", idx.SourceCount(), idx.ConceptCount())

	// Load concept bodies for full-content grep (LWC-17 Gap 2 fix)
	if err := idx.LoadConceptBodies(context.Background(), gcsClient); err != nil {
		log.Printf("WARNING: Concept body loading failed: %v", err)
	} else {
		log.Printf("Concept bodies loaded: %d concepts", idx.ConceptCount())
	}

	// Project-scoped concept cache for the V1 query path.
	conceptCache := conceptcache.New()
	if entries, err := conceptCache.Build(context.Background(), gcsClient); err != nil {
		log.Printf("WARNING: Concept cache build failed: %v", err)
	} else {
		log.Printf("Concept cache: %d concepts", len(entries))
	}

	// LLM client (optional — query works without it)
	llmClient := llm.NewClient(cfg.DeepSeekAPIKey)
	if llmClient != nil {
		log.Printf("LLM client: DeepSeek ready")
	} else {
		log.Printf("LLM client: DEEPSEEK_API_KEY not set — query synthesis disabled")
	}

	// Query expander (lifestyle domain for MVP)
	expander, err := llm.NewExpander(llmClient, "lifestyle")
	if err != nil {
		log.Printf("Query expander: %v", err)
	} else if expander != nil {
		log.Printf("Query expander: lifestyle domain ready")
	}

		// OpenTelemetry metrics (graceful fallback)
		provider, err := observability.InitMetrics(context.Background(), "llm-wiki-bff-dev", observability.GetProjectID())
		if err != nil {
			log.Printf("[observability] WARNING: metrics init failed (continuing): %v", err)
		} else {
			defer func() {
				if err := provider.Shutdown(context.Background()); err != nil {
					log.Printf("[observability] metrics shutdown error: %v", err)
				}
			}()
		}

		// Handlers
		h := handler.New(gcsClient, fsClient, idx, llmClient, expander)
	hV1 := handlerv1.New(gcsClient, fsClient, idx, conceptCache, llmClient, expander, cfg.DefaultUserID)

	// Gin router
		r := gin.Default()

	// OpenTelemetry latency middleware (per-endpoint)
	r.Use(middleware.LatencyMiddleware())

	// CORS — must be BEFORE routes
	r.Use(corsMiddleware())
	r.Use(defaultRequestScope(cfg))

	// Public auth routes (no auth middleware)
	r.POST("/api/v1/auth/login", auth.LoginHandler(fsClient.Raw(), cfg.JWTSecret))

	// ── Swagger UI ──
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ── API ──
	api := r.Group("/api")
	{
		api.POST("/query", h.Query)              // {"q": "...", "mode": "wiki|full"}
		api.GET("/sources", h.ListSources)       // list compiled wiki sources
		api.GET("/sources/:slug", h.GetSource)   // get single source content
		api.GET("/concepts", h.ListConcepts)     // list wiki concepts (including drafts)
		api.GET("/concepts/:slug", h.GetConcept) // get single concept
		api.POST("/import", h.Import)            // bookmark import (placeholder)
		api.GET("/status", h.Status)             // pipeline status

		// Metrics (Grafana)
		api.GET("/metrics", h.Metrics)         // pipeline execution metrics
		r.GET("/metrics", h.PrometheusMetrics) // Prometheus format (root level)

		// Raw content management
		api.POST("/raw/upload", h.UploadRaw)             // upload .md file to raw/
		api.POST("/raw/scrape", h.ScrapeRaw)             // scrape URL → raw/
		api.POST("/raw/generate-title", h.GenerateTitle) // LLM title from content

		// Pipeline
		api.POST("/pipeline/run", h.RunPipeline) // trigger OLW pipeline
	}

	// ── API v1 (with JWT auth + project routing) ──
	v1 := r.Group("/api/v1")
	v1.Use(auth.JWTAuth(cfg))
	v1.Use(auth.ProjectMiddleware())
	{
		v1.GET("/health", hV1.Health)
		v1.POST("/query", hV1.Query)
		v1.GET("/sources", hV1.ListSources)
		v1.GET("/sources/:slug", hV1.GetSource)
		v1.GET("/concepts", hV1.ListConcepts)
		v1.GET("/concepts/:slug", hV1.GetConcept)
		v1.POST("/import", hV1.Import)
		v1.POST("/pipeline/run", hV1.PipelineRun)
		v1.GET("/status", hV1.Status)
		v1.GET("/metrics", hV1.PrometheusMetrics)
	}

	// ── Static frontend ──
	r.StaticFile("/", "./static/index.html")
	r.Static("/static", "./static")
	r.NoRoute(func(c *gin.Context) {
		// SPA fallback: serve index.html for non-API routes
		if !strings.HasPrefix(c.Request.URL.Path, "/api") {
			c.File("./static/index.html")
		}
	})

	log.Printf("BFF listening on :%s", cfg.Port)
	log.Printf("Swagger UI: http://localhost:%s/swagger/index.html", cfg.Port)
	log.Fatal(r.Run(":" + cfg.Port))
}

func corsMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-User-ID, X-Project-ID")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}
		c.Next()
	}
}

func defaultRequestScope(cfg config.Config) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Set("userID", cfg.UserID)
		c.Set("projectID", cfg.ProjectID)
		c.Next()
	}
}
